### ISSUE TITLE
uncaughtException: invalid large-object descriptor

### ISSUE THREAD

**Issue by yanickrochon** [Joris-van-der-Wel/node-pg-large-object#1]
I get an uncaughtException when trying to access more than one large object at once.

The app I'm writing is a webservice that's storing larg files into Postgres, then retrieved via secure URLs. The problem is that a browser may request content in parallel, and many browsers can do as well. But, to fix this issue, I'd need to build a queue system. However, is there any way to fix this on this module's end?

```
error: uncaughtException: invalid large-object descriptor: 1 
   [ 'Error: invalid large-object descriptor: 1',
     '    at Connection.parseE (/home/xxxxx/dev/vitex/node_modules/pg.js/lib/connection.js:534:11)',
     '    at Connection.parseMessage (/home/xxxxx/dev/vitex/node_modules/pg.js/lib/connection.js:361:17)',
     '    at Socket.<anonymous> (/home/xxxxx/dev/vitex/node_modules/pg.js/lib/connection.js:105:22)',
     '    at Socket.EventEmitter.emit (events.js:107:17)',
     '    at readableAddChunk (_stream_readable.js:159:16)',
     '    at Socket.Readable.push (_stream_readable.js:126:10)',
     '    at TCP.onread (net.js:514:20)' ] }
```

**Comment by Joris-van-der-Wel** [comment]
I have not seen this error before. Are you sure that you are using a transaction, even when reading a large object?  The open, read and close must all be within the same transaction (this is a limitation of postgres).

Note that pg-large-object does _not_ create a transaction for you in any of its methods. (I tried to mimic the postgres java library)

I use this to serve files using express & sequelize. I just did a load test using `ab -c 100 -n 100 http://localhost:1337/foo/bar` and I never saw that error (-c is for concurrent connections).

**Comment by yanickrochon** [comment]
The app is using `co` and `koa.js` to serve files, and perhaps this the main difference. This is the code I have (it works) : 

``` js
var locks = [];

var suspend = require('co-suspend');
var LargeObjectManager = require('pg-large-object').LargeObjectManager;
var Connections = require('beyo-model-mapper').Connections;

function * getStream(oid) {
  var marker = suspend();
  var adapter = yield Connections.get(options.adapter);
  var lo = new LargeObjectManager(adapter);

  if (locks.locked) {
    locks.push(marker);
    yield marker.wait();
  }

  locks.locked = true;

  // When working with Large Objects, always use a transaction 
  adapter.query('BEGIN', function(err, result) {
    if (err) {
      marker.resume(err);
    } else {
      lo.openAndReadableStream(oid, BUFFER_SIZE, function(err, size, stream) {
        if (err) {
          marker.resume(err);
        } else {
          stream.on('end', function() {
            adapter.query('COMMIT');

            locks.locked = false;

            if (locks.length) {
              locks.pop().resume();
            }
          });

          marker.resume(null, stream);
        }
      });
    }
  });

  return yield marker.wait();
};
```

I sometimes forget that not everyone works with yieldables :)

But, also this same problem will occur if you ever switch to a Promise/A+ base API.

**Comment by Joris-van-der-Wel** [comment]
The unit tests in this repository are all done using promises ;)

Although nowadays I use bluebird instead of q.

``` javascript
var Promise = require('bluebird');
var LargeObjectManager = require('pg-large-object').LargeObjectManager;
Promise.promisifyAll(LargeObjectManager.prototype); // adds *Async methods

return sequelize.transaction(function (transaction)
{
    var man = new LargeObjectManager(transaction.connection);
    return man.openAsync(123).then(function(obj)
    {
        return [obj, obj.sizeAsync()];
    }).spread(function(obj, size)
    {
        console.log('size is', size);
        return obj.closeAsync();
    });
});
```

I do not really get around using ES6 yeild because browser support is lagging.
